spring.application.name=mock_trello
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:51103/railway
spring.datasource.username=root
spring.datasource.password=QzBIsVHHjMGJhmsWhYPvQiUSDMUXsLEJ
spring.jpa.hibernate.ddl-auto=update